version: '3.8'

services: 
  postgres:
    container_name: 'postgres'
    env_file: ./backend/docker.env
    build: 
      context: ./backend
      dockerfile: dockerfile.db 
    ports:
      - '5050:5050'
    volumes:
      - ./.database/postgres/data:/data/
  api: 
    container_name: 'api'
    env_file: ./backend/docker.env
    build: 
      context: ./backend
      dockerfile: dockerfile.api
    ports:
      - '3030:3030'
    depends_on:
      - postgres
    restart: always
  front:
    container_name: 'front'
    build: 
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - api
    restart: always